server:
  port: 9099
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      write_dates_as_timestamps: false
  elasticsearch:
    rest:
      uris: localhost:9200

#elasticsearch:
#  uri: localhost:9200

json:
  files:
    - classpath:1.json
    - classpath:2.json