server:
  port: 8083
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      write_dates_as_timestamps: false
  elasticsearch:
    rest:
      uris: elasticsearch:9200

json:
  loans: classpath:loans.json
  persons: classpath:persons.json