version: "3.8"
services:
  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  alfabattle-elastic:
    container_name: alfabattle-elastic
    depends_on:
      - elastic
    image: aminetor/alfabattle_elastic:1.0-SNAPSHOT
    ports:
      - 9099:9099